# Generated by Django 4.2.3 on 2023-08-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='amenities',
            field=models.CharField(choices=[('airport', (('potty_location', 'Potty Location'), ('water', 'Water'))), ('amusement_park', (('potty_location', 'Potty Location'), ('water', 'Water'), ('dog_friendly_rides', 'Dog-Friendly Rides'))), ('aquarium', (('potty_location', 'Potty Location'), ('water', 'Water'))), ('art_gallery', (('potty_location', 'Potty Location'), ('water', 'Water'), ('pet_friendly_exhibits', 'Pet-Friendly Exhibits'))), ('bakery', (('dog_treats', 'Dog Treats'), ('outdoor_seating', 'Outdoor Seating'))), ('cafe', (('dog_treats', 'Dog Treats'), ('outdoor_seating', 'Outdoor Seating'), ('peaceful_walking_area', 'Peaceful Walking Area'))), ('park', (('off_leash_area', 'Off-Leash Area'), ('peaceful_walking_area', 'Peaceful Walking Area'), ('waste_bags', 'Waste Bags'), ('water', 'Water'))), ('beach', (('off_leash_area', 'Off-Leash Area'), ('water', 'Water'), ('waste_bags', 'Waste Bags'))), ('campground', (('off_leash_area', 'Off-Leash Area'), ('peaceful_walking_area', 'Peaceful Walking Area'), ('waste_bags', 'Waste Bags'))), ('pet_store', (('dog_treats', 'Dog Treats'), ('pet_supplies', 'Pet Supplies'))), ('vet_clinic', (('dog_friendly_waiting_area', 'Dog-Friendly Waiting Area'), ('pet_healthcare', 'Pet Healthcare'))), ('grooming_salon', (('dog_grooming_services', 'Dog Grooming Services'),))], default='', max_length=200),
        ),
    ]
