# Generated by Django 4.2.3 on 2023-08-06 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_place_profile_alter_profile_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='review date'),
        ),
    ]
