# Generated by Django 4.2.3 on 2023-08-05 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_place_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('airport', (('potty_location', 'Potty Location'), ('water', 'Water'))), ('amusement_park', (('potty_location', 'Potty Location'), ('water', 'Water'), ('dog_friendly_rides', 'Dog-Friendly Rides'))), ('aquarium', (('potty_location', 'Potty Location'), ('water', 'Water'))), ('art_gallery', (('potty_location', 'Potty Location'), ('water', 'Water'), ('pet_friendly_exhibits', 'Pet-Friendly Exhibits'))), ('bakery', (('dog_treats', 'Dog Treats'), ('outdoor_seating', 'Outdoor Seating'))), ('cafe', (('dog_treats', 'Dog Treats'), ('outdoor_seating', 'Outdoor Seating'), ('peaceful_walking_area', 'Peaceful Walking Area'))), ('park', (('off_leash_area', 'Off-Leash Area'), ('peaceful_walking_area', 'Peaceful Walking Area'), ('waste_bags', 'Waste Bags'), ('water', 'Water'))), ('beach', (('off_leash_area', 'Off-Leash Area'), ('water', 'Water'), ('waste_bags', 'Waste Bags'))), ('campground', (('off_leash_area', 'Off-Leash Area'), ('peaceful_walking_area', 'Peaceful Walking Area'), ('waste_bags', 'Waste Bags'))), ('pet_store', (('dog_treats', 'Dog Treats'), ('pet_supplies', 'Pet Supplies'))), ('vet_clinic', (('dog_friendly_waiting_area', 'Dog-Friendly Waiting Area'), ('pet_healthcare', 'Pet Healthcare'))), ('grooming_salon', (('dog_grooming_services', 'Dog Grooming Services'),))], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='place',
            name='amenities',
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField()),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.amenity')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='amenities',
            field=models.ManyToManyField(related_name='places', to='main_app.amenity'),
        ),
    ]
