# Generated by Django 4.2.3 on 2023-08-01 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_pet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='pets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.pet'),
        ),
    ]
