# Generated by Django 4.2.3 on 2023-08-02 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_place_description_alter_place_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='description',
        ),
    ]
