# Generated by Django 4.2.3 on 2023-08-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_place_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
