# Generated by Django 4.2.3 on 2023-08-01 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_pet_profile_profile_pets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pets',
        ),
        migrations.AddField(
            model_name='pet',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.profile'),
        ),
    ]
