# Generated by Django 4.2.3 on 2023-08-02 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_place_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='rating',
        ),
    ]
