# Generated by Django 4.2.3 on 2023-08-01 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_profile_pets_pet_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='main_app.profile'),
        ),
    ]
