# Generated by Django 4.2.3 on 2023-08-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_profile_latitude_profile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
