# Generated by Django 4.2.3 on 2023-08-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='photos_limit',
            field=models.IntegerField(default=3),
        ),
    ]
