# Generated by Django 4.2.3 on 2023-08-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(to='main_app.place'),
        ),
    ]
